### ISSUE TITLE
with texlive 2013, it gives out many errors

### ISSUE THREAD

**Issue by braindevices** [peterwittek/test-latex-converters#1]
Hi Peter,

Thanks a lot for creating this nice test package. However, there is no figure in odt file at all. The hyperlink also created at wrong places.
htlatex has very ugly inlinemath and tables:
![htlatex_inlinemath](https://cloud.githubusercontent.com/assets/7507440/5710080/0e06fee0-9a54-11e4-8870-148166be0ceb.png)
![htlatex_table](https://cloud.githubusercontent.com/assets/7507440/5710085/150c7bc0-9a54-11e4-9f25-bfbec317c491.png)
ODT has wrong hyperlink positions:
![tex4ht_hyperlinks](https://cloud.githubusercontent.com/assets/7507440/5710089/17b154ea-9a54-11e4-9934-901d81e2ce38.png)
cannot read images:
![tex5ht_figures](https://cloud.githubusercontent.com/assets/7507440/5710090/19067f14-9a54-11e4-9f37-003586e643ff.png)

**Comment by peterwittek** [comment]
Hi,

Thanks for trying this repo and for filing this issue. I looked into the problems you pointed out, and I am afraid what you are witnessing is not the fault of the test cases, but of the tools tested.

I used TeXLive 2014, which needed an extra patch to run the tests:

http://tex.stackexchange.com/questions/185349/error-using-pgfsysdriver-with-tex4ht-only-shows-up-with-texlive-2014-ok-with-t

You are right, htlatex has ugly inline math and tables -- this is expected. The odt file still does not have the images, this is also expected. It has been over a year since I created these tests, but not much progress has been made by the conversion tools. Pandoc has some neat tricks which I either missed earlier or they are new. The following command does a good job at creating a fairly faithful HTML rendering of the LaTeX file:

```
pandoc --mathml --self-contained --bibliography=./bibliography.bib -o ./results/test_case_pandoc_with_mathml.html test_case.tex
```

Unfortunately, when read from LibreOffice, it looks terrible. If you don't mind using the services of Google, the HTML produced by this command shows okay in LibreOffice:

```
pandoc --webtex --self-contained --bibliography=./bibliography.bib -o ./results/test_case_pandoc_with_webtex.html test_case.tex
```

The additional disadvantage is that the embedded images of the equations have to be resized.

So I think htlatex is still the best solution, with some manual adjustments of the result to make it less ugly. If you stumble on a better solution, I would be glad to hear of it.

**Comment by braindevices** [comment]
Thanks a lot! I also realized it is a pgf driver problem and got it patched.

So far for pure HTML generation, the LaTeXML is the best solution I've every tried at least all the MathML are correct and the tables are beatiful. 

But its Plugin::Doc which generate ODT is still under development which has not seen any progress for 6 months. The oolatex actually get all the equestions wrong, which treat most equations as plain text with superscript and subscript.

FYI, the LaTeXML can be directly applied onto test_case.tex with script found here:
http://www.albany.edu/~hammond/demos/Html5/arXiv/lxmlexamples.html

**Comment by peterwittek** [comment]
This is great, I was not aware of LaTeXML. The HTML4 output of this tool with the images embedded is by far the best option. I updated to Makefile to include this conversion. Thanks very much for the suggestion!

If you agree, I think we could close this issue.
